import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  bg: { flex: 1, backgroundColor: '#121212' },
  scrollContainer: { padding: 20, paddingTop: 60, alignItems: 'center' },
  container: { flex: 1, justifyContent: 'center', backgroundColor: '#000' },
  text: { color: '#fff', textAlign: 'center', fontSize: 18, marginBottom: 20 },
  headerTitle: { color: '#00D1B2', fontSize: 32, fontWeight: '900', marginBottom: 20, letterSpacing: 1 },
  card: {
    backgroundColor: '#1E1E1E', borderRadius: 16, padding: 20, width: '100%',
    marginBottom: 20, borderWidth: 1, borderColor: '#333',
    shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 10,
  },
  itemCard: {
    backgroundColor: '#242424', borderRadius: 12, padding: 12, width: '100%',
    marginBottom: 10, borderWidth: 1, borderColor: '#444',
  },
  itemHeader: { color: '#00D1B2', fontSize: 18, fontWeight: 'bold', marginBottom: 10 },
  splitRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  backBtn: { padding: 5 },
  backBtnText: { color: '#00D1B2', fontSize: 16, fontWeight: 'bold' },
  cardTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', marginBottom: 15 },
  previewImage: { width: '100%', height: 200, borderRadius: 10, marginBottom: 15, resizeMode: 'cover' },
  imageList: { flexDirection: 'row', marginBottom: 15 },
  imageContainer: { marginRight: 10, position: 'relative' },
  thumbnail: { width: 120, height: 160, borderRadius: 8, resizeMode: 'cover' },
  removeBtn: { position: 'absolute', top: -5, right: -5, backgroundColor: '#FF3B30', width: 24, height: 24, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  removeBtnText: { color: '#fff', fontSize: 12, fontWeight: 'bold' },
  placeholderBox: { width: '100%', height: 150, borderRadius: 10, backgroundColor: '#2C2C2C', justifyContent: 'center', alignItems: 'center', marginBottom: 15 },
  placeholderText: { color: '#777', fontSize: 16 },
  row: { flexDirection: 'row', justifyContent: 'space-between' },
  actionBtn: { flex: 1, backgroundColor: '#00D1B2', padding: 12, borderRadius: 8, marginRight: 5, alignItems: 'center' },
  actionBtnAlt: { flex: 1, backgroundColor: 'transparent', borderWidth: 1, borderColor: '#00D1B2', padding: 12, borderRadius: 8, marginLeft: 5, alignItems: 'center' },
  btnText: { color: '#000', fontWeight: 'bold', fontSize: 16 },
  btnTextAlt: { color: '#00D1B2', fontWeight: 'bold', fontSize: 16 },
  analyzeBtn: { backgroundColor: '#FF3B30', padding: 18, borderRadius: 12, width: '100%', alignItems: 'center', marginTop: 10, shadowColor: '#FF3B30', shadowOpacity: 0.4, shadowRadius: 10 },
  analyzeBtnText: { color: '#fff', fontWeight: '900', fontSize: 18 },
  approveBtn: { backgroundColor: '#34C759', padding: 18, borderRadius: 12, width: '100%', alignItems: 'center', marginTop: 10, marginBottom: 10, shadowColor: '#34C759', shadowOpacity: 0.4, shadowRadius: 10 },
  camera: { flex: 1 },
  buttonContainer: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, flexDirection: 'column', backgroundColor: 'transparent', justifyContent: 'flex-end', alignItems: 'center', paddingBottom: 40 },
  captureButton: { width: 70, height: 70, borderRadius: 35, backgroundColor: 'rgba(255,255,255,0.3)', justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
  captureButtonInner: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#fff' },
  cancelButton: { padding: 15, alignItems: 'center' },
  flashBtn: { position: 'absolute', top: 50, right: 20, backgroundColor: 'rgba(0,0,0,0.6)', padding: 10, borderRadius: 8 },
  button: { backgroundColor: '#00D1B2', padding: 15, borderRadius: 8, marginTop: 20 },
  buttonText: { color: '#000', fontSize: 18, fontWeight: 'bold' },
  label: { color: '#aaa', fontSize: 12, fontWeight: 'bold', marginTop: 10, marginBottom: 5 },
  valueText: { color: '#fff', fontSize: 14, marginBottom: 5 },
  input: { backgroundColor: '#1A1A1A', color: '#fff', padding: 8, borderRadius: 6, fontSize: 14, borderWidth: 1, borderColor: '#555' },
  highlightInput: { borderColor: '#00D1B2', borderWidth: 1.5, backgroundColor: '#0A1A17' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.7)' },
  modalContent: { backgroundColor: '#1E1E1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, maxHeight: 300 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  modalTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  modalCloseText: { color: '#00D1B2', fontSize: 16, fontWeight: 'bold' },
  modalOption: { paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#333', alignItems: 'center' },
  modalOptionText: { color: '#fff', fontSize: 18 },
  uploadingOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  statusText: {
    color: '#fff',
    fontSize: 10,
    marginTop: 4,
    fontWeight: 'bold',
  },
  completedBadge: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 10,
    padding: 2,
  },
  failedBadge: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 10,
    padding: 2,
  }
});

export default styles;
